---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: saudade
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: registry.deti:5000/saudade/payment:latest
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
      volumes:
      - name: app-secret
        secret:
          secretName: payment-secret

# CREATE SERVICE FOR APP
---
apiVersion: v1
kind: Service
metadata:
  name: paymentservice
  namespace: saudade
spec:
  ports:
  - port: 6000
    targetPort: 5000
  selector:
    app: payment

# Configure Traefik
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: payment-k3s
  namespace: saudade
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
    traefik.ingress.kubernetes.io/custom-response-headers: "Access-Control-Allow-Origin:*||Access-Control-Allow-Methods:GET,PUT,DELETE,POST,OPTIONS||Access-Control-Allow-Headers:auth,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range||Access-Control-Expose-Headers:Content-Length,Content-Range"

spec:
  rules:
  - host: payment.k3s
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: paymentservice
            port: 
              number: 6000