---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: saudade
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: registry.deti:5000/saudade/app
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
      volumes:
      - name: app-secret
        secret:
          secretName: app-secret


# Create nginx deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: saudade
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx:alpine
          name: nginx
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
          - name: nginx-saudade-pvc
            mountPath: /var/www/static
          - name: nginx-conf
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
            readOnly: true
      restartPolicy: Always
      volumes:
      - name: nginx-saudade-pvc
        persistentVolumeClaim:
          claimName: nginx-saudade-pvc
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
             - key: nginx.conf
               path: nginx.conf

# CREATE SERVICE FOR APP
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: saudade
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: app


# Create Service for APP
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: saudade
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx

# Configure Traefik
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: saudade-app-k3s
  namespace: saudade
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  rules:
  - host: payment-saudade.k3s
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port: 
              number: 80

# NGINX Config map
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: saudade
data:
  nginx.conf: |
    user  nginx;
    worker_processes  1;
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;
    events {
            worker_connections  1024;
    }
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        sendfile        on;
        server {
            listen 80 default_server;
            server_name app.k3s;
            location / {
                proxy_pass http://app:8080/;
             }
            location /static {
                root /var/www;
           }
        }
    }