version: '3'
services:
  flask:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: flask
    image: digitalocean.com/flask-python:3.10.4
    restart: unless-stopped
    environment:
      APP_ENV: "prod"
      APP_DEBUG: "False"
      APP_PORT: 5000
      MONGODB_DATABASE: flaskdb
      MONGODB_USERNAME: flaskpayment
      MONGODB_PASSWORD: payment
      MONGODB_HOSTNAME: mongodb
    volumes:
      - appdata:/var/www
    depends_on:
      - mongodb
    networks:
      - backend
  # Mongo DB database configuration
  mongodb:
    image: mongo:4.4.4
    container_name: paymentdb
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: paymentdb
      MONGO_INITDB_ROOT_PASSWORD: payment
      MONGO_INITDB_DATABASE: flaskdb
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend

  # networks:
  #   backend:
  #     driver: bridge


  # volumes:
  #   mongodbdata:
  #     driver: local
  #   appdata:
  #     driver: local