apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pv-claim
  namespace: saudade
  labels:
    app: mongodb-payment
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300M
---
apiVersion: apps/v1
kind: Deployment # what to create?
metadata:
  name: mongodb-payment
  namespace: saudade
spec: # specification for deployment resource
  replicas: 1 # how many replicas of pods we want to create
  selector:
    matchLabels:
      app: mongodb-payment
  template: # blueprint for pods
    metadata:
      labels:
        app: mongodb-payment # service will look for this label
    spec: # specification for pods
      containers: # we can have one or more containers
      - name: mariadb
        image: registry.deti:5000/saudade/mongo:v2
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-pv
          mountPath: /var/lib/mysql
      volumes:
      - name: mongodb-pv
        persistentVolumeClaim:
          claimName: mongodb-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: paymentmongodb
  namespace: saudade
spec:
  selector:
    app: mongodb-payment
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017